### ISSUE TITLE
Optimize Send send16bitData Routine

### ISSUE THREAD

**Issue by zwenson** [FriedlTheFox/LedMatrixDriver#10]
Routine gets faster because at the beginning the shift is 15bit and at the the end 1 bit that influences also the clock timing.

**Comment by FriedlTheFox** [comment]
At the moment the duration is 52.125us for sending 16 bits
[5.5us .. 1.125us]

**Comment by FriedlTheFox** [comment]
With the new function we need 15.5us to send 16 bit :laughing:
